# Generated by Django 6.0.3 on 2026-04-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch')], max_length=20)),
                ('current_episode', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
