# Generated by Django 6.0.3 on 2026-04-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_posts_delete_anime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='post',
        ),
    ]
