# Generated by Django 6.0.3 on 2026-04-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_posts_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='anime',
        ),
    ]
