# Generated by Django 6.0.3 on 2026-04-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_rename_post_anime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anime',
            new_name='Anime_List',
        ),
    ]
