# Generated by Django 6.0.3 on 2026-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_rename_anime_anime_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_list',
            name='is_completed',
            field=models.BooleanField(default=1),
            preserve_default=True,
        ),
    ]
