# Generated by Django 6.0.3 on 2026-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_anime_list_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_list',
            name='is_completed',
            field=models.BooleanField(),
        ),
    ]
